import helloworld.*

class BootStrap {

    def init = { servletContext ->

        println "***Bootstrap***"

        if(!Team.count()){

            println "***Adding Teams***"

            // AFC East
            new Team(name: "New England Patriots")
                    .addToPlayers(name:'Joseph Addai',pos: 'RB')
                    .addToPlayers(name:'Brandon Bolden',pos: 'RB')
                    .addToPlayers(name:'Tom Brady',pos: 'QB')
                    .addToPlayers(name:'Deion Branch',pos: 'WR')
                    .addToPlayers(name:'Britt Davis',pos: 'WR')
                    .addToPlayers(name:'Jeremy Ebert',pos: 'WR')
                    .addToPlayers(name:'Julian Edelman',pos: 'WR')
                    .addToPlayers(name:'Daniel Fells',pos: 'TE')
                    .addToPlayers(name:'Tony Fiammetta',pos: 'RB')
                    .addToPlayers(name:'Jabar Gaffney',pos: 'WR')
                    .addToPlayers(name:'Anthony Gonzalez',pos: 'WR')
                    .addToPlayers(name:'Rob Gronkowski',pos: 'TE')
                    .addToPlayers(name:'Brad Herman',pos: 'TE')
                    .addToPlayers(name:'Aaron Hernandez',pos: 'TE')
                    .addToPlayers(name:'Brian Hoyer',pos: 'QB')
                    .addToPlayers(name:'Eric Kettani',pos: 'RB')
                    .addToPlayers(name:'Spencer Larsen',pos: 'RB')
                    .addToPlayers(name:'Brandon Lloyd',pos: 'WR')
                    .addToPlayers(name:'Ryan Mallett',pos: 'QB')
                    .addToPlayers(name:'Chad Ochocinco',pos: 'WR')
                    .addToPlayers(name:'Stevan Ridley',pos: 'RB')
                    .addToPlayers(name:'Matt Roark',pos: 'WR')
                    .addToPlayers(name:'Matthew Slater',pos: 'WR')
                    .addToPlayers(name:'Donte Stallworth',pos: 'WR')
                    .addToPlayers(name:'Shane Vereen',pos: 'RB')
                    .addToPlayers(name:'Wes Welker',pos: 'WR')
                    .addToPlayers(name:'Danny Woodhead',pos: 'RB')
                    .save(failOnError: true)
            new Team(name: "New York Jets")
                    .addToPlayers(name:'Josh Baker',pos: 'RB')
                    .addToPlayers(name:'John Conner',pos: 'RB')
                    .addToPlayers(name:'Jeff Cumberland',pos: 'TE')
                    .addToPlayers(name:'Dedrick Epps',pos: 'TE')
                    .addToPlayers(name:'DaMarcus Ganaway',pos: 'WR')
                    .addToPlayers(name:'Terrance Ganaway',pos: 'RB')
                    .addToPlayers(name:'Shonn Greene',pos: 'RB')
                    .addToPlayers(name:'John Griffin',pos: 'RB')
                    .addToPlayers(name:'Stephen Hill',pos: 'WR')
                    .addToPlayers(name:'Santonio Holmes',pos: 'WR')
                    .addToPlayers(name:'Dexter Jackson',pos: 'WR')
                    .addToPlayers(name:'Dustin Keller',pos: 'TE')
                    .addToPlayers(name:'Jeremy Kerley',pos: 'WR')
                    .addToPlayers(name:'G.J. Kinne',pos: 'QB')
                    .addToPlayers(name:'Brian Linthicum',pos: 'TE')
                    .addToPlayers(name:'Greg McElroy',pos: 'QB')
                    .addToPlayers(name:'Joe McKnight',pos: 'RB')
                    .addToPlayers(name:'Scotty McKnight',pos: 'WR')
                    .addToPlayers(name:'Royce Pollard',pos: 'WR')
                    .addToPlayers(name:'Bilal Powell',pos: 'RB')
                    .addToPlayers(name:'Eron Riley',pos: 'WR')
                    .addToPlayers(name:'Mark Sanchez',pos: 'QB')
                    .addToPlayers(name:'Chaz Schilens',pos: 'WR')
                    .addToPlayers(name:'Matt Simms',pos: 'QB')
                    .addToPlayers(name:'Hayden Smith',pos: 'TE')
                    .addToPlayers(name:'Tim Tebow',pos: 'QB')
                    .addToPlayers(name:'Patrick Turner',pos: 'WR')
                    .addToPlayers(name:'Jordan White',pos: 'WR')
                    .save(failOnError: true)
            new Team(name: "Miami Dolphins")
                    .addToPlayers(name:'Davone Bess',pos: 'WR')
                    .addToPlayers(name:'Les Brown',pos: 'TE')
                    .addToPlayers(name:'Reggie Bush',pos: 'RB')
                    .addToPlayers(name:'Charles Clay',pos: 'RB')
                    .addToPlayers(name:'B.J. Cunningham',pos: 'WR')
                    .addToPlayers(name:'Pat Devlin',pos: 'QB')
                    .addToPlayers(name:'Michael Egnew',pos: 'TE')
                    .addToPlayers(name:'Anthony Fasano',pos: 'TE')
                    .addToPlayers(name:'Jeff Fuller',pos: 'WR')
                    .addToPlayers(name:'David Garrard',pos: 'QB')
                    .addToPlayers(name:'Clyde Gates',pos: 'WR')
                    .addToPlayers(name:'Jonas Gray',pos: 'RB')
                    .addToPlayers(name:'Brian Hartline',pos: 'WR')
                    .addToPlayers(name:'Chris Hogan',pos: 'WR')
                    .addToPlayers(name:'Jeron Mastrud',pos: 'TE')
                    .addToPlayers(name:'Rishard Matthews',pos: 'WR')
                    .addToPlayers(name:'Jerome Messam',pos: 'RB')
                    .addToPlayers(name:'Lamar Miller',pos: 'RB')
                    .addToPlayers(name:'Marlon Moore',pos: 'WR')
                    .addToPlayers(name:'Matt Moore',pos: 'QB')
                    .addToPlayers(name:'Derek Moye',pos: 'WR')
                    .addToPlayers(name:'Legedu Naanee',pos: 'WR')
                    .addToPlayers(name:'Julius Pruitt',pos: 'WR')
                    .addToPlayers(name:'Steve Slaton',pos: 'RB')
                    .addToPlayers(name:'Ryan Tannehill',pos: 'QB')
                    .addToPlayers(name:'Marcus Thigpen',pos: 'RB')
                    .addToPlayers(name:'Daniel Thomas',pos: 'RB')
                    .addToPlayers(name:'Roberto Wallace',pos: 'WR')
                    .addToPlayers(name:'Will Yeatman',pos: 'TE')
                    .save(failOnError: true)
            new Team(name: "Buffalo Bills")
                    .addToPlayers(name:'Kamar Aiken',pos: 'WR')
                    .addToPlayers(name:'Kevin Brock',pos: 'TE')
                    .addToPlayers(name:'Mike Caussin',pos: 'TE')
                    .addToPlayers(name:'Scott Chandler',pos: 'TE')
                    .addToPlayers(name:'Tashard Choice',pos: 'RB')
                    .addToPlayers(name:'David Clowney',pos: 'WR')
                    .addToPlayers(name:'Dorin Dickerson',pos: 'WR')
                    .addToPlayers(name:'Chris Douglas',pos: 'RB')
                    .addToPlayers(name:'Marcus Easley',pos: 'WR')
                    .addToPlayers(name:'Ryan Fitzpatrick',pos: 'QB')
                    .addToPlayers(name:'T.J. Graham',pos: 'WR')
                    .addToPlayers(name:'Derek Hagan',pos: 'WR')
                    .addToPlayers(name:'Fred Jackson',pos: 'RB')
                    .addToPlayers(name:'Stevie Johnson',pos: 'WR')
                    .addToPlayers(name:'Donald Jones',pos: 'WR')
                    .addToPlayers(name:'Ruvell Martin',pos: 'WR')
                    .addToPlayers(name:'Corey McIntyre',pos: 'RB')
                    .addToPlayers(name:'David Nelson',pos: 'WR')
                    .addToPlayers(name:'Fendi Onobun',pos: 'TE')
                    .addToPlayers(name:'Naaman Roosevelt',pos: 'WR')
                    .addToPlayers(name:'Brad Smith',pos: 'WR')
                    .addToPlayers(name:'Lee Smith',pos: 'TE')
                    .addToPlayers(name:'C.J. Spiller',pos: 'RB')
                    .addToPlayers(name:'Tyler Thigpen',pos: 'QB')
                    .addToPlayers(name:'Johnny White',pos: 'RB')
                    .addToPlayers(name:'Vince Young',pos: 'QB')
                    .save(failOnError: true)

            // AFC North
            new Team(name: "Baltimore Ravens")
                    .addToPlayers(name:'Anthony Allen',pos: 'RB')
                    .addToPlayers(name:'Matt Balasavage',pos: 'TE')
                    .addToPlayers(name:'Damien Berry',pos: 'RB')
                    .addToPlayers(name:'Anquan Boldin',pos: 'WR')
                    .addToPlayers(name:'Rodney Bradley',pos: 'WR')
                    .addToPlayers(name:'John Brantley',pos: 'QB')
                    .addToPlayers(name:'Ed Dickson',pos: 'TE')
                    .addToPlayers(name:'Chad Diehl',pos: 'RB')
                    .addToPlayers(name:'Tandon Doss',pos: 'WR')
                    .addToPlayers(name:'Davon Drew',pos: 'TE')
                    .addToPlayers(name:'Bruce Figgins',pos: 'TE')
                    .addToPlayers(name:'Joe Flacco',pos: 'QB')
                    .addToPlayers(name:'Devin Goda',pos: 'WR')
                    .addToPlayers(name:'Dorian Graham',pos: 'WR')
                    .addToPlayers(name:'Jacoby Jones',pos: 'WR')
                    .addToPlayers(name:'Vonta Leach',pos: 'RB')
                    .addToPlayers(name:'Phillip Livas',pos: 'WR')
                    .addToPlayers(name:'Curtis Painter',pos: 'QB')
                    .addToPlayers(name:'Brandon Pendergrass',pos: 'RB')
                    .addToPlayers(name:'Bernard Pierce',pos: 'RB')
                    .addToPlayers(name:'Dennis Pitta',pos: 'TE')
                    .addToPlayers(name:'Bobby Rainey',pos: 'RB')
                    .addToPlayers(name:'David Reed',pos: 'WR')
                    .addToPlayers(name:'Ray Rice',pos: 'RB')
                    .addToPlayers(name:'Torrey Smith',pos: 'WR')
                    .addToPlayers(name:'Chester Stewart',pos: 'QB')
                    .addToPlayers(name:'Tommy Streeter',pos: 'WR')
                    .addToPlayers(name:'Tyrod Taylor',pos: 'QB')
                    .addToPlayers(name:'Deonte Thompson',pos: 'WR')
                    .addToPlayers(name:'LaQuan Williams',pos: 'WR')
                    .addToPlayers(name:'Patrick Williams',pos: 'WR')
                    .save(failOnError: true)

            new Team(name: "Pittsburgh Steelers")
                    .addToPlayers(name:'Baron Batch',pos: 'RB')
                    .addToPlayers(name:'Charlie Batch',pos: 'QB')
                    .addToPlayers(name:'Tyler Beiler',pos: 'WR')
                    .addToPlayers(name:'Antonio Brown',pos: 'WR')
                    .addToPlayers(name:'John Clay',pos: 'RB')
                    .addToPlayers(name:'Toney Clemons',pos: 'WR')
                    .addToPlayers(name:'Jerricho Cotchery',pos: 'WR')
                    .addToPlayers(name:'Connor Dixon',pos: 'WR')
                    .addToPlayers(name:'Jonathan Dwyer',pos: 'RB')
                    .addToPlayers(name:'David Gilreath',pos: 'WR')
                    .addToPlayers(name:'David Johnson',pos: 'TE')
                    .addToPlayers(name:'Jerrod Johnson',pos: 'QB')
                    .addToPlayers(name:'Will Johnson',pos: 'RB')
                    .addToPlayers(name:'Byron Leftwich',pos: 'QB')
                    .addToPlayers(name:'Wes Lyons',pos: 'TE')
                    .addToPlayers(name:'Marquis Maze',pos: 'WR')
                    .addToPlayers(name:'Jamie McCoy',pos: 'TE')
                    .addToPlayers(name:'Rashard Mendenhall',pos: 'RB')
                    .addToPlayers(name:'Heath Miller',pos: 'TE')
                    .addToPlayers(name:'David Paulson',pos: 'TE')
                    .addToPlayers(name:'Leonard Pope',pos: 'TE')
                    .addToPlayers(name:'Chris Rainey',pos: 'RB')
                    .addToPlayers(name:'Isaac Redman',pos: 'RB')
                    .addToPlayers(name:'Ben Roethlisberger',pos: 'QB')
                    .addToPlayers(name:'Emmanuel Sanders',pos: 'WR')
                    .addToPlayers(name:'Weslye Saunders',pos: 'TE')
                    .addToPlayers(name:'Troy Smith',pos: 'QB')
                    .addToPlayers(name:'Juamorris Stewart',pos: 'WR')
                    .addToPlayers(name:'Mike Wallace',pos: 'WR')
                    .addToPlayers(name:'Derrick Williams',pos: 'WR')
                    .addToPlayers(name:'Jimmy Young',pos: 'WR')
                    .save(failOnError: true)

            new Team(name: "Cincinnati Bengals")
                    .addToPlayers(name:'Armon Binns',pos: 'WR')
                    .addToPlayers(name:'Jourdan Brooks',pos: 'RB')
                    .addToPlayers(name:'Aaron Brown',pos: 'RB')
                    .addToPlayers(name:'Orson Charles',pos: 'TE')
                    .addToPlayers(name:'Colin Cochart',pos: 'TE')
                    .addToPlayers(name:'Andy Dalton',pos: 'QB')
                    .addToPlayers(name:'Bryce Davis',pos: 'TE')
                    .addToPlayers(name:'James Develin',pos: 'RB')
                    .addToPlayers(name:'Bruce Gradkowski',pos: 'QB')
                    .addToPlayers(name:'A.J. Green',pos: 'WR')
                    .addToPlayers(name:'BenJarvus Green-Ellis',pos: 'RB')
                    .addToPlayers(name:'Jermaine Gresham',pos: 'TE')
                    .addToPlayers(name:'Tyler Hansen',pos: 'QB')
                    .addToPlayers(name:'Clark Harris',pos: 'TE')
                    .addToPlayers(name:'Andrew Hawkins',pos: 'WR')
                    .addToPlayers(name:'Vidal Hazelton',pos: 'WR')
                    .addToPlayers(name:'Dan Herron',pos: 'RB')
                    .addToPlayers(name:'Justin Hilton',pos: 'WR')
                    .addToPlayers(name:'Marvin Jones',pos: 'WR')
                    .addToPlayers(name:'Donald Lee',pos: 'TE')
                    .addToPlayers(name:'Brian Leonard',pos: 'RB')
                    .addToPlayers(name:'Kashif Moore',pos: 'WR')
                    .addToPlayers(name:'Cedric Peerman',pos: 'RB')
                    .addToPlayers(name:'Chris Pressley',pos: 'RB')
                    .addToPlayers(name:'Zac Robinson',pos: 'QB')
                    .addToPlayers(name:'Taveon Rogers',pos: 'WR')
                    .addToPlayers(name:'Mohamed Sanu',pos: 'WR')
                    .addToPlayers(name:'Bernard Scott',pos: 'RB')
                    .addToPlayers(name:'Jordan Shipley',pos: 'WR')
                    .addToPlayers(name:'Rodney Stewart',pos: 'RB')
                    .addToPlayers(name:'Brandon Tate',pos: 'WR')
                    .addToPlayers(name:'Ryan Whalen',pos: 'WR')
                    .save(failOnError: true)

            new Team(name: "Cleveland Browns")
                    .addToPlayers(name:'Travis Benjamin',pos: 'WR')
                    .addToPlayers(name:'Jordan Cameron',pos: 'TE')
                    .addToPlayers(name:'Josh Cooper',pos: 'WR')
                    .addToPlayers(name:'Joshua Cribbs',pos: 'WR')
                    .addToPlayers(name:'Dan Gronkowski',pos: 'TE')
                    .addToPlayers(name:'Montario Hardesty',pos: 'RB')
                    .addToPlayers(name:'Brandon Jackson',pos: 'RB')
                    .addToPlayers(name:'Thaddeus Lewis',pos: 'QB')
                    .addToPlayers(name:'Greg Little',pos: 'WR')
                    .addToPlayers(name:'Owen Marecic',pos: 'RB')
                    .addToPlayers(name:'Mohamed Massaquoi',pos: 'WR')
                    .addToPlayers(name:'Colt McCoy',pos: 'QB')
                    .addToPlayers(name:'Carlton Mitchell',pos: 'WR')
                    .addToPlayers(name:'Evan Moore',pos: 'TE')
                    .addToPlayers(name:'Jordan Norwood',pos: 'WR')
                    .addToPlayers(name:'Chris Ogbonnaya',pos: 'RB')
                    .addToPlayers(name:'Bert Reed',pos: 'WR')
                    .addToPlayers(name:'Trent Richardson',pos: 'RB')
                    .addToPlayers(name:'Jermaine Saffold',pos: 'WR')
                    .addToPlayers(name:'Brad Smelley',pos: 'RB')
                    .addToPlayers(name:'Alex Smith',pos: 'TE')
                    .addToPlayers(name:'Owen Spencer',pos: 'WR')
                    .addToPlayers(name:'Adonis Thomas',pos: 'RB')
                    .addToPlayers(name:'Seneca Wallace',pos: 'QB')
                    .addToPlayers(name:'Benjamin Watson',pos: 'TE')
                    .addToPlayers(name:'Brandon Weeden',pos: 'QB')
                    .addToPlayers(name:'Eddie Williams',pos: 'RB')
                    .addToPlayers(name:'Rod Windsor',pos: 'WR')
                    .save(failOnError: true)

            // AFC South
            new Team(name: "Houston Texans")
                    .addToPlayers(name:'John Beck',pos: 'QB')
                    .addToPlayers(name:'Logan Brock',pos: 'TE')
                    .addToPlayers(name:'James Casey',pos: 'RB')
                    .addToPlayers(name:'Owen Daniels',pos: 'TE')
                    .addToPlayers(name:'Jason Ford',pos: 'RB')
                    .addToPlayers(name:'Arian Foster',pos: 'RB')
                    .addToPlayers(name:'Garrett Graham',pos: 'TE')
                    .addToPlayers(name:'Jonathan Grimes',pos: 'RB')
                    .addToPlayers(name:'Trindon Holliday',pos: 'WR')
                    .addToPlayers(name:'Juaquin Iglesias',pos: 'WR')
                    .addToPlayers(name:'Jerrell Jackson',pos: 'WR')
                    .addToPlayers(name:'Lester Jean',pos: 'WR')
                    .addToPlayers(name:'Andre Johnson',pos: 'WR')
                    .addToPlayers(name:'Dwight Jones',pos: 'WR')
                    .addToPlayers(name:'Case Keenum',pos: 'QB')
                    .addToPlayers(name:'Mario Louis',pos: 'WR')
                    .addToPlayers(name:'Jeff Maehl',pos: 'WR')
                    .addToPlayers(name:'Keshawn Martin',pos: 'WR')
                    .addToPlayers(name:'Davin Meggett',pos: 'RB')
                    .addToPlayers(name:'DeVier Posey',pos: 'WR')
                    .addToPlayers(name:'Matt Schaub',pos: 'QB')
                    .addToPlayers(name:'Phillip Supernaw',pos: 'TE')
                    .addToPlayers(name:'Ben Tate',pos: 'RB')
                    .addToPlayers(name:'Kevin Walter',pos: 'WR')
                    .addToPlayers(name:'Javarris Williams',pos: 'RB')
                    .addToPlayers(name:'T.J. Yates',pos: 'QB')
                    .save(failOnError: true)

            new Team(name: "Tennessee Titans")
                    .addToPlayers(name:'Devin Aguilar',pos: 'WR')
                    .addToPlayers(name:'Brandon Barden',pos: 'TE')
                    .addToPlayers(name:'Beau Brinkley',pos: 'TE')
                    .addToPlayers(name:'Kenny Britt',pos: 'WR')
                    .addToPlayers(name:'Jared Cook',pos: 'TE')
                    .addToPlayers(name:'Chase Deadder',pos: 'WR')
                    .addToPlayers(name:'Herb Donaldson',pos: 'RB')
                    .addToPlayers(name:'LaQuinton Evans',pos: 'WR')
                    .addToPlayers(name:'Cameron Graham',pos: 'TE')
                    .addToPlayers(name:'Daniel Graham',pos: 'TE')
                    .addToPlayers(name:'Jamie Harper',pos: 'RB')
                    .addToPlayers(name:'Matt Hasselbeck',pos: 'QB')
                    .addToPlayers(name:'Lavelle Hawkins',pos: 'WR')
                    .addToPlayers(name:'Chris Johnson',pos: 'RB')
                    .addToPlayers(name:'Quinn Johnson',pos: 'RB')
                    .addToPlayers(name:'James Kirkendoll',pos: 'WR')
                    .addToPlayers(name:'Jake Locker',pos: 'QB')
                    .addToPlayers(name:'Marc Mariani',pos: 'WR')
                    .addToPlayers(name:'Collin Mooney',pos: 'RB')
                    .addToPlayers(name:'O.J. Murdock',pos: 'WR')
                    .addToPlayers(name:'Michael Preston',pos: 'WR')
                    .addToPlayers(name:'Darius Reynaud',pos: 'RB')
                    .addToPlayers(name:'Javon Ringer',pos: 'RB')
                    .addToPlayers(name:'Rusty Smith',pos: 'QB')
                    .addToPlayers(name:'Nick Stephens',pos: 'QB')
                    .addToPlayers(name:'Craig Stevens',pos: 'TE')
                    .addToPlayers(name:'Taylor Thompson',pos: 'TE')
                    .addToPlayers(name:'Nate Washington',pos: 'WR')
                    .addToPlayers(name:'Darryl Whiting',pos: 'RB')
                    .addToPlayers(name:'Damian Williams',pos: 'WR')
                    .addToPlayers(name:'D.J. Woods',pos: 'WR')
                    .addToPlayers(name:'Kendall Wright',pos: 'WR')
                    .save(failOnError: true)

            new Team(name: "Jacksonville Jaguars")
                    .addToPlayers(name:'Justin Blackmon',pos: 'WR')
                    .addToPlayers(name:'Brock Bolen',pos: 'RB')
                    .addToPlayers(name:'Mike Brown',pos: 'WR')
                    .addToPlayers(name:'Colin Cloherty',pos: 'TE')
                    .addToPlayers(name:'Kevin Elliott',pos: 'WR')
                    .addToPlayers(name:'Lee Evans',pos: 'WR')
                    .addToPlayers(name:'Chris Forcier',pos: 'WR')
                    .addToPlayers(name:'Blaine Gabbert',pos: 'QB')
                    .addToPlayers(name:'DuJuan Harris',pos: 'RB')
                    .addToPlayers(name:'Chad Henne',pos: 'QB')
                    .addToPlayers(name:'Rashad Jennings',pos: 'RB')
                    .addToPlayers(name:'Greg Jones',pos: 'RB')
                    .addToPlayers(name:'Maurice Jones-Drew',pos: 'RB')
                    .addToPlayers(name:'Marcedes Lewis',pos: 'TE')
                    .addToPlayers(name:'Zach Miller',pos: 'TE')
                    .addToPlayers(name:'Richard Murphy',pos: 'RB')
                    .addToPlayers(name:'Montell Owens',pos: 'RB')
                    .addToPlayers(name:'Jordan Palmer',pos: 'QB')
                    .addToPlayers(name:'Jalen Parmele',pos: 'RB')
                    .addToPlayers(name:'Zach Potter',pos: 'TE')
                    .addToPlayers(name:'Taylor Price',pos: 'WR')
                    .addToPlayers(name:'Laurent Robinson',pos: 'WR')
                    .addToPlayers(name:'Brian Robiskie',pos: 'WR')
                    .addToPlayers(name:'Cecil Shorts',pos: 'WR')
                    .addToPlayers(name:'Naufahu Tahi',pos: 'RB')
                    .addToPlayers(name:'Mike Thomas',pos: 'WR')
                    .addToPlayers(name:'Matt Veldman',pos: 'TE')
                    .addToPlayers(name:'Chastin West',pos: 'WR')
                    .save(failOnError: true)

            new Team(name: "Indianapolis Colts")
                    .addToPlayers(name:'Dwayne Allen',pos: 'TE')
                    .addToPlayers(name:'Donnie Avery',pos: 'WR')
                    .addToPlayers(name:'Vick Ballard',pos: 'RB')
                    .addToPlayers(name:'LaVon Brazill',pos: 'WR')
                    .addToPlayers(name:'Donald Brown',pos: 'RB')
                    .addToPlayers(name:'Delone Carter',pos: 'RB')
                    .addToPlayers(name:'Austin Collie',pos: 'WR')
                    .addToPlayers(name:'Quan Cosby',pos: 'WR')
                    .addToPlayers(name:'Darren Evans',pos: 'RB')
                    .addToPlayers(name:'Jarred Fayson',pos: 'WR')
                    .addToPlayers(name:'Coby Fleener',pos: 'TE')
                    .addToPlayers(name:'Chris Gronkowski',pos: 'RB')
                    .addToPlayers(name:'Chandler Harnish',pos: 'QB')
                    .addToPlayers(name:'T.Y. Hilton',pos: 'WR')
                    .addToPlayers(name:'Dominique Jones',pos: 'TE')
                    .addToPlayers(name:'Deji Karim',pos: 'RB')
                    .addToPlayers(name:'Andrew Luck',pos: 'QB')
                    .addToPlayers(name:'Ryan Mahaffey',pos: 'RB')
                    .addToPlayers(name:'Kyle Miller',pos: 'TE')
                    .addToPlayers(name:'Jeremy Ross',pos: 'WR')
                    .addToPlayers(name:'Jabin Sambrano',pos: 'WR')
                    .addToPlayers(name:'Andre Smith',pos: 'TE')
                    .addToPlayers(name:'Justin Snow',pos: 'TE')
                    .addToPlayers(name:'Drew Stanton',pos: 'QB')
                    .addToPlayers(name:'Trevor Vittatoe',pos: 'QB')
                    .addToPlayers(name:'Reggie Wayne',pos: 'WR')
                    .addToPlayers(name:'Griff Whalen',pos: 'WR')
                    .save(failOnError: true)

            // AFC West
            new Team(name: "Denver Broncos")
                    .addToPlayers(name:'Lance Ball',pos: 'RB')
                    .addToPlayers(name:'Andre Caldwell',pos: 'WR')
                    .addToPlayers(name:'Eric Decker',pos: 'WR')
                    .addToPlayers(name:'Mark Dell',pos: 'WR')
                    .addToPlayers(name:'Joel Dreessen',pos: 'TE')
                    .addToPlayers(name:'Mario Fannin',pos: 'RB')
                    .addToPlayers(name:'DAndre Goodwin',pos: 'WR')
                    .addToPlayers(name:'Virgil Green',pos: 'TE')
                    .addToPlayers(name:'Tyler Grisham',pos: 'WR')
                    .addToPlayers(name:'Caleb Hanie',pos: 'QB')
                    .addToPlayers(name:'Jason Hill',pos: 'WR')
                    .addToPlayers(name:'Ronnie Hillman',pos: 'RB')
                    .addToPlayers(name:'Cornelius Ingram',pos: 'TE')
                    .addToPlayers(name:'Jeremiah Johnson',pos: 'RB')
                    .addToPlayers(name:'Peyton Manning',pos: 'QB')
                    .addToPlayers(name:'Willis McGahee',pos: 'RB')
                    .addToPlayers(name:'Anthony Miller',pos: 'TE')
                    .addToPlayers(name:'Knowshon Moreno',pos: 'RB')
                    .addToPlayers(name:'Xavier Omon',pos: 'RB')
                    .addToPlayers(name:'Greg Orton',pos: 'WR')
                    .addToPlayers(name:'Brock Osweiler',pos: 'QB')
                    .addToPlayers(name:'Eric Page',pos: 'WR')
                    .addToPlayers(name:'Gerell Robinson',pos: 'WR')
                    .addToPlayers(name:'Brandon Stokley',pos: 'WR')
                    .addToPlayers(name:'Austin Sylvester',pos: 'RB')
                    .addToPlayers(name:'Jacob Tamme',pos: 'TE')
                    .addToPlayers(name:'Demaryius Thomas',pos: 'WR')
                    .addToPlayers(name:'Julius Thomas',pos: 'TE')
                    .addToPlayers(name:'Adam Weber',pos: 'QB')
                    .addToPlayers(name:'Matt Willis',pos: 'WR')
                    .save(failOnError: true)

            new Team(name: "San Diego Chargers")
                    .addToPlayers(name:'Hubert Anyiam',pos: 'WR')
                    .addToPlayers(name:'Edwin Baker',pos: 'RB')
                    .addToPlayers(name:'Jason Barnes',pos: 'WR')
                    .addToPlayers(name:'Curtis Brinkley',pos: 'RB')
                    .addToPlayers(name:'Vincent Brown',pos: 'WR')
                    .addToPlayers(name:'Paul Cox',pos: 'WR')
                    .addToPlayers(name:'Taylor Embree',pos: 'WR')
                    .addToPlayers(name:'Malcom Floyd',pos: 'WR')
                    .addToPlayers(name:'Antonio Gates',pos: 'TE')
                    .addToPlayers(name:'Richard Goodman',pos: 'WR')
                    .addToPlayers(name:'Ladarius Green',pos: 'TE')
                    .addToPlayers(name:'Nick Guess',pos: 'TE')
                    .addToPlayers(name:'Michael Hayes',pos: 'RB')
                    .addToPlayers(name:'Jacob Hester',pos: 'RB')
                    .addToPlayers(name:'Jarrett Lee',pos: 'QB')
                    .addToPlayers(name:'Mohamed Marah',pos: 'RB')
                    .addToPlayers(name:'Ryan Mathews',pos: 'RB')
                    .addToPlayers(name:'LeRon McClain',pos: 'RB')
                    .addToPlayers(name:'Randy McMichael',pos: 'TE')
                    .addToPlayers(name:'Robert Meachem',pos: 'WR')
                    .addToPlayers(name:'Roscoe Parrish',pos: 'WR')
                    .addToPlayers(name:'Phillip Payne',pos: 'WR')
                    .addToPlayers(name:'Philip Rivers',pos: 'QB')
                    .addToPlayers(name:'Dante Rosario',pos: 'TE')
                    .addToPlayers(name:'Eddie Royal',pos: 'WR')
                    .addToPlayers(name:'Kory Sperry',pos: 'TE')
                    .addToPlayers(name:'Micheal Spurlock',pos: 'WR')
                    .addToPlayers(name:'Brad Taylor',pos: 'TE')
                    .addToPlayers(name:'Charlie Whitehurst',pos: 'QB')
                    .addToPlayers(name:'Mike Willie',pos: 'WR')
                    .save(failOnError: true)

            new Team(name: "Oakland Raiders")
                    .addToPlayers(name:'David Ausberry',pos: 'TE')
                    .addToPlayers(name:'Rhett Bomar',pos: 'QB')
                    .addToPlayers(name:'Duke Calhoun',pos: 'WR')
                    .addToPlayers(name:'Derek Carrier',pos: 'WR')
                    .addToPlayers(name:'Brandon Carswell',pos: 'WR')
                    .addToPlayers(name:'Juron Criner',pos: 'WR')
                    .addToPlayers(name:'Kyle Efaw',pos: 'TE')
                    .addToPlayers(name:'Jacoby Ford',pos: 'WR')
                    .addToPlayers(name:'Mike Goodson',pos: 'RB')
                    .addToPlayers(name:'Richard Gordon',pos: 'TE')
                    .addToPlayers(name:'Andre Hardy',pos: 'TE')
                    .addToPlayers(name:'Darrius Heyward-Bey',pos: 'WR')
                    .addToPlayers(name:'Rashawn Jackson',pos: 'RB')
                    .addToPlayers(name:'Taiwan Jones',pos: 'RB')
                    .addToPlayers(name:'Matt Leinart',pos: 'QB')
                    .addToPlayers(name:'Thomas Mayo',pos: 'WR')
                    .addToPlayers(name:'Darren McFadden',pos: 'RB')
                    .addToPlayers(name:'Eddie McGee',pos: 'WR')
                    .addToPlayers(name:'Lonyae Miller',pos: 'RB')
                    .addToPlayers(name:'Denarius Moore',pos: 'WR')
                    .addToPlayers(name:'Louis Murphy',pos: 'WR')
                    .addToPlayers(name:'Brandon Myers',pos: 'TE')
                    .addToPlayers(name:'Carson Palmer',pos: 'QB')
                    .addToPlayers(name:'Terrelle Pryor',pos: 'QB')
                    .addToPlayers(name:'Marcel Reece',pos: 'RB')
                    .addToPlayers(name:'TreShawn Robinson',pos: 'RB')
                    .addToPlayers(name:'Owen Schmitt',pos: 'RB')
                    .addToPlayers(name:'Travionte Session',pos: 'WR')
                    .addToPlayers(name:'Rod Streater',pos: 'WR')
                    .addToPlayers(name:'Manase Tonga',pos: 'RB')
                    .save(failOnError: true)

            new Team(name: "Kansas City Chiefs")
                    .addToPlayers(name:'Jonathan Baldwin',pos: 'WR')
                    .addToPlayers(name:'Shane Bannon',pos: 'RB')
                    .addToPlayers(name:'Josh Bellamy',pos: 'WR')
                    .addToPlayers(name:'Tim Biere',pos: 'TE')
                    .addToPlayers(name:'Kevin Boss',pos: 'TE')
                    .addToPlayers(name:'Dwayne Bowe',pos: 'WR')
                    .addToPlayers(name:'Steve Breaston',pos: 'WR')
                    .addToPlayers(name:'Matt Cassel',pos: 'QB')
                    .addToPlayers(name:'Jamaal Charles',pos: 'RB')
                    .addToPlayers(name:'Terrance Copper',pos: 'WR')
                    .addToPlayers(name:'Shaun Draughn',pos: 'RB')
                    .addToPlayers(name:'Nate Eachus',pos: 'RB')
                    .addToPlayers(name:'Taylor Gentry',pos: 'RB')
                    .addToPlayers(name:'Cyrus Gray',pos: 'RB')
                    .addToPlayers(name:'Junior Hemingway',pos: 'WR')
                    .addToPlayers(name:'Peyton Hillis',pos: 'RB')
                    .addToPlayers(name:'Jeremy Horne',pos: 'WR')
                    .addToPlayers(name:'Brandon Kinnie',pos: 'WR')
                    .addToPlayers(name:'Steve Maneri',pos: 'TE')
                    .addToPlayers(name:'Zeke Markshausen',pos: 'WR')
                    .addToPlayers(name:'Dexter McCluster',pos: 'RB')
                    .addToPlayers(name:'Tony Moeaki',pos: 'TE')
                    .addToPlayers(name:'Jamar Newsome',pos: 'WR')
                    .addToPlayers(name:'Jake OConnell',pos: 'TE')
                    .addToPlayers(name:'Brady Quinn',pos: 'QB')
                    .addToPlayers(name:'Martin Rucker',pos: 'TE')
                    .addToPlayers(name:'Ricky Stanzi',pos: 'QB')
                    .addToPlayers(name:'Devon Wylie',pos: 'WR')
                    .save(failOnError: true)

            // NFC East
            new Team(name: "New York Giants")
                    .addToPlayers(name:'Jake Ballard',pos: 'TE')
                    .addToPlayers(name:'Ramses Barden',pos: 'WR')
                    .addToPlayers(name:'Travis Beckum',pos: 'TE')
                    .addToPlayers(name:'Martellus Bennett',pos: 'TE')
                    .addToPlayers(name:'Ahmad Bradshaw',pos: 'RB')
                    .addToPlayers(name:'Andre Brown',pos: 'RB')
                    .addToPlayers(name:'David Carr',pos: 'QB')
                    .addToPlayers(name:'Brandon Collins',pos: 'WR')
                    .addToPlayers(name:'Victor Cruz',pos: 'WR')
                    .addToPlayers(name:'Dan DePalma',pos: 'WR')
                    .addToPlayers(name:'Larry Donnell',pos: 'TE')
                    .addToPlayers(name:'David Douglas',pos: 'WR')
                    .addToPlayers(name:'Domenik Hixon',pos: 'WR')
                    .addToPlayers(name:'Christian Hopkins',pos: 'TE')
                    .addToPlayers(name:'Henry Hynoski',pos: 'RB')
                    .addToPlayers(name:'Jerrel Jernigan',pos: 'WR')
                    .addToPlayers(name:'Eli Manning',pos: 'QB')
                    .addToPlayers(name:'Joe Martinek',pos: 'RB')
                    .addToPlayers(name:'Hakeem Nicks',pos: 'WR')
                    .addToPlayers(name:'Bear Pascoe',pos: 'TE')
                    .addToPlayers(name:'Ryan Perrilloux',pos: 'QB')
                    .addToPlayers(name:'Ryan Purvis',pos: 'TE')
                    .addToPlayers(name:'Rueben Randle',pos: 'WR')
                    .addToPlayers(name:'Adrien Robinson',pos: 'TE')
                    .addToPlayers(name:'DaRel Scott',pos: 'RB')
                    .addToPlayers(name:'Isaiah Stanback',pos: 'WR')
                    .addToPlayers(name:'Julian Talley',pos: 'WR')
                    .addToPlayers(name:'D.J. Ware',pos: 'RB')
                    .addToPlayers(name:'David Wilson',pos: 'RB')
                    .save(failOnError: true)

            new Team(name: "Philadelphia Eagles")
                    .addToPlayers(name:'Elvis Akpla',pos: 'WR')
                    .addToPlayers(name:'Jason Avant',pos: 'WR')
                    .addToPlayers(name:'Brett Brackett',pos: 'TE')
                    .addToPlayers(name:'Bryce Brown',pos: 'RB')
                    .addToPlayers(name:'Brent Celek',pos: 'TE')
                    .addToPlayers(name:'Graig Cooper',pos: 'RB')
                    .addToPlayers(name:'Riley Cooper',pos: 'WR')
                    .addToPlayers(name:'Trent Edwards',pos: 'QB')
                    .addToPlayers(name:'Nick Foles',pos: 'QB')
                    .addToPlayers(name:'Chase Ford',pos: 'TE')
                    .addToPlayers(name:'Mardy Gilyard',pos: 'WR')
                    .addToPlayers(name:'Chad Hall',pos: 'WR')
                    .addToPlayers(name:'Jamel Hamler',pos: 'WR')
                    .addToPlayers(name:'Clay Harbor',pos: 'TE')
                    .addToPlayers(name:'Jacory Harris',pos: 'QB')
                    .addToPlayers(name:'Stanley Havili',pos: 'RB')
                    .addToPlayers(name:'Emil Igwenagu',pos: 'RB')
                    .addToPlayers(name:'DeSean Jackson',pos: 'WR')
                    .addToPlayers(name:'McKay Jacobson',pos: 'WR')
                    .addToPlayers(name:'Damaris Johnson',pos: 'WR')
                    .addToPlayers(name:'Ronald Johnson',pos: 'WR')
                    .addToPlayers(name:'Mike Kafka',pos: 'QB')
                    .addToPlayers(name:'Dion Lewis',pos: 'RB')
                    .addToPlayers(name:'Jeremy Maclin',pos: 'WR')
                    .addToPlayers(name:'LeSean McCoy',pos: 'RB')
                    .addToPlayers(name:'Marvin McNutt',pos: 'WR')
                    .addToPlayers(name:'Aaron Pflugrad',pos: 'WR')
                    .addToPlayers(name:'Chris Polk',pos: 'RB')
                    .addToPlayers(name:'Jeremy Stewart',pos: 'RB')
                    .addToPlayers(name:'Michael Vick',pos: 'QB')
                    .save(failOnError: true)

            new Team(name: "Dallas Cowboys")
                    .addToPlayers(name:'Miles Austin',pos: 'WR')
                    .addToPlayers(name:'Cole Beasley',pos: 'WR')
                    .addToPlayers(name:'Tim Benford',pos: 'WR')
                    .addToPlayers(name:'George Bryan',pos: 'TE')
                    .addToPlayers(name:'Dez Bryant',pos: 'WR')
                    .addToPlayers(name:'Rudy Carpenter',pos: 'QB')
                    .addToPlayers(name:'Shaun Chapas',pos: 'RB')
                    .addToPlayers(name:'Danny Coale',pos: 'WR')
                    .addToPlayers(name:'Lance Dunbar',pos: 'RB')
                    .addToPlayers(name:'Isaiah Greenhouse',pos: 'RB')
                    .addToPlayers(name:'Saalim Hakim',pos: 'WR')
                    .addToPlayers(name:'James Hanna',pos: 'TE')
                    .addToPlayers(name:'Dwayne Harris',pos: 'WR')
                    .addToPlayers(name:'Andre Holmes',pos: 'WR')
                    .addToPlayers(name:'Felix Jones',pos: 'RB')
                    .addToPlayers(name:'Donavon Kemp',pos: 'WR')
                    .addToPlayers(name:'Stephen McGee',pos: 'QB')
                    .addToPlayers(name:'DeMarco Murray',pos: 'RB')
                    .addToPlayers(name:'Kevin Ogletree',pos: 'WR')
                    .addToPlayers(name:'Kyle Orton',pos: 'QB')
                    .addToPlayers(name:'John Phillips',pos: 'TE')
                    .addToPlayers(name:'Raymond Radway',pos: 'WR')
                    .addToPlayers(name:'Tony Romo',pos: 'QB')
                    .addToPlayers(name:'Darrell Scott',pos: 'RB')
                    .addToPlayers(name:'Andrew Szczerba',pos: 'TE')
                    .addToPlayers(name:'Phillip Tanner',pos: 'RB')
                    .addToPlayers(name:'Lawrence Vickers',pos: 'RB')
                    .addToPlayers(name:'Jason Witten',pos: 'TE')
                    .save(failOnError: true)

            new Team(name: "Washington Redskins")
                    .addToPlayers(name:'Anthony Armstrong',pos: 'WR')
                    .addToPlayers(name:'Terrence Austin',pos: 'WR')
                    .addToPlayers(name:'Antwon Bailey',pos: 'RB')
                    .addToPlayers(name:'Brandon Banks',pos: 'WR')
                    .addToPlayers(name:'Chris Cooley',pos: 'TE')
                    .addToPlayers(name:'Kirk Cousins',pos: 'QB')
                    .addToPlayers(name:'Lennon Creer',pos: 'RB')
                    .addToPlayers(name:'Jonathan Crompton',pos: 'QB')
                    .addToPlayers(name:'Fred Davis',pos: 'TE')
                    .addToPlayers(name:'Tristan Davis',pos: 'RB')
                    .addToPlayers(name:'Pierre Garcon',pos: 'WR')
                    .addToPlayers(name:'Robert Griffin III',pos: 'QB')
                    .addToPlayers(name:'Rex Grossman',pos: 'QB')
                    .addToPlayers(name:'Leonard Hankerson',pos: 'WR')
                    .addToPlayers(name:'Darius Hanks',pos: 'WR')
                    .addToPlayers(name:'Roy Helu',pos: 'RB')
                    .addToPlayers(name:'Brian Hernandez',pos: 'WR')
                    .addToPlayers(name:'Tim Hightower',pos: 'RB')
                    .addToPlayers(name:'Sam Kirkland',pos: 'WR')
                    .addToPlayers(name:'Lance Lewis',pos: 'WR')
                    .addToPlayers(name:'Josh Morgan',pos: 'WR')
                    .addToPlayers(name:'Alfred Morris',pos: 'RB')
                    .addToPlayers(name:'Santana Moss',pos: 'WR')
                    .addToPlayers(name:'Rob Myers',pos: 'TE')
                    .addToPlayers(name:'Niles Paul',pos: 'WR')
                    .addToPlayers(name:'Logan Paulsen',pos: 'TE')
                    .addToPlayers(name:'Richard Quinn',pos: 'TE')
                    .addToPlayers(name:'Beau Reliford',pos: 'TE')
                    .addToPlayers(name:'Aldrick Robinson',pos: 'WR')
                    .addToPlayers(name:'Evan Royster',pos: 'RB')
                    .addToPlayers(name:'Darrel Young',pos: 'RB')
                    .save(failOnError: true)

            // NFC North
            new Team(name: "Green Bay Packers")
                    .addToPlayers(name:'Duane Bennett',pos: 'RB')
                    .addToPlayers(name:'Diondre Borel',pos: 'WR')
                    .addToPlayers(name:'Jarrett Boykin',pos: 'WR')
                    .addToPlayers(name:'Randall Cobb',pos: 'WR')
                    .addToPlayers(name:'B.J. Coleman',pos: 'QB')
                    .addToPlayers(name:'Nic Cooper',pos: 'RB')
                    .addToPlayers(name:'Tom Crabtree',pos: 'TE')
                    .addToPlayers(name:'Donald Driver',pos: 'WR')
                    .addToPlayers(name:'Jermichael Finley',pos: 'TE')
                    .addToPlayers(name:'Cameron Ford',pos: 'TE')
                    .addToPlayers(name:'Curenski Gilleylen',pos: 'WR')
                    .addToPlayers(name:'Alex Green',pos: 'RB')
                    .addToPlayers(name:'Tori Gurley',pos: 'WR')
                    .addToPlayers(name:'Nick Hill',pos: 'QB')
                    .addToPlayers(name:'Jon Hoese',pos: 'RB')
                    .addToPlayers(name:'Greg Jennings',pos: 'WR')
                    .addToPlayers(name:'James Jones',pos: 'WR')
                    .addToPlayers(name:'John Kuhn',pos: 'RB')
                    .addToPlayers(name:'Eric Lair',pos: 'TE')
                    .addToPlayers(name:'Dale Moss',pos: 'WR')
                    .addToPlayers(name:'Jordy Nelson',pos: 'WR')
                    .addToPlayers(name:'Andrew Quarless',pos: 'TE')
                    .addToPlayers(name:'Marcus Rivers',pos: 'WR')
                    .addToPlayers(name:'Aaron Rodgers',pos: 'QB')
                    .addToPlayers(name:'Brandon Saine',pos: 'RB')
                    .addToPlayers(name:'Shaky Smithson',pos: 'WR')
                    .addToPlayers(name:'James Starks',pos: 'RB')
                    .addToPlayers(name:'Ryan Taylor',pos: 'TE')
                    .addToPlayers(name:'Marc Tyler',pos: 'RB')
                    .addToPlayers(name:'D.J. Williams',pos: 'TE')
                    .save(failOnError: true)

            new Team(name: "Detroit Lions")
                    .addToPlayers(name:'Joique Bell',pos: 'RB')
                    .addToPlayers(name:'Jahvid Best',pos: 'RB')
                    .addToPlayers(name:'Ryan Broyles',pos: 'WR')
                    .addToPlayers(name:'James Bryant',pos: 'RB')
                    .addToPlayers(name:'Nate Burleson',pos: 'WR')
                    .addToPlayers(name:'Troy Burrell',pos: 'WR')
                    .addToPlayers(name:'Patrick Edwards',pos: 'WR')
                    .addToPlayers(name:'Alex Gottlieb',pos: 'TE')
                    .addToPlayers(name:'Stephfon Green',pos: 'RB')
                    .addToPlayers(name:'Marcus Harris',pos: 'WR')
                    .addToPlayers(name:'Will Heller',pos: 'TE')
                    .addToPlayers(name:'Shaun Hill',pos: 'QB')
                    .addToPlayers(name:'Nate Hughes',pos: 'WR')
                    .addToPlayers(name:'Calvin Johnson',pos: 'WR')
                    .addToPlayers(name:'Jared Karstetter',pos: 'WR')
                    .addToPlayers(name:'Mikel LeShoure',pos: 'RB')
                    .addToPlayers(name:'Stefan Logan',pos: 'WR')
                    .addToPlayers(name:'Lance Long',pos: 'WR')
                    .addToPlayers(name:'Wallace Miles',pos: 'WR')
                    .addToPlayers(name:'Kellen Moore',pos: 'QB')
                    .addToPlayers(name:'Nathan Overbay',pos: 'TE')
                    .addToPlayers(name:'Brandon Pettigrew',pos: 'TE')
                    .addToPlayers(name:'Tony Scheffler',pos: 'TE')
                    .addToPlayers(name:'Kevin Smith',pos: 'RB')
                    .addToPlayers(name:'Matthew Stafford',pos: 'QB')
                    .addToPlayers(name:'Terrence Toliver',pos: 'WR')
                    .addToPlayers(name:'Austin Wells',pos: 'TE')
                    .addToPlayers(name:'Keiland Williams',pos: 'RB')
                    .addToPlayers(name:'Titus Young',pos: 'WR')
                    .save(failOnError: true)

            new Team(name: "Chicago Bears")
                    .addToPlayers(name:'Kyle Adams',pos: 'TE')
                    .addToPlayers(name:'Alvester Alexander',pos: 'RB')
                    .addToPlayers(name:'Armando Allen',pos: 'RB')
                    .addToPlayers(name:'Joseph Anderson',pos: 'WR')
                    .addToPlayers(name:'Kahlil Bell',pos: 'RB')
                    .addToPlayers(name:'Earl Bennett',pos: 'WR')
                    .addToPlayers(name:'Matt Blanchard',pos: 'QB')
                    .addToPlayers(name:'Michael Bush',pos: 'RB')
                    .addToPlayers(name:'Jason Campbell',pos: 'QB')
                    .addToPlayers(name:'Tyler Clutts',pos: 'RB')
                    .addToPlayers(name:'Terriun Crump',pos: 'WR')
                    .addToPlayers(name:'Jay Cutler',pos: 'QB')
                    .addToPlayers(name:'Kellen Davis',pos: 'TE')
                    .addToPlayers(name:'Nathan Enderle',pos: 'QB')
                    .addToPlayers(name:'Matt Forte',pos: 'RB')
                    .addToPlayers(name:'Brittan Golden',pos: 'WR')
                    .addToPlayers(name:'Devin Hester',pos: 'WR')
                    .addToPlayers(name:'Alshon Jeffery',pos: 'WR')
                    .addToPlayers(name:'Johnny Knox',pos: 'WR')
                    .addToPlayers(name:'Brandon Marshall',pos: 'WR')
                    .addToPlayers(name:'Josh McCown',pos: 'QB')
                    .addToPlayers(name:'Evan Rodriguez',pos: 'TE')
                    .addToPlayers(name:'Draylen Ross',pos: 'TE')
                    .addToPlayers(name:'Dane Sanzenbacher',pos: 'WR')
                    .addToPlayers(name:'Matt Spaeth',pos: 'TE')
                    .addToPlayers(name:'Chris Summers',pos: 'WR')
                    .addToPlayers(name:'Devin Thomas',pos: 'WR')
                    .addToPlayers(name:'Harvey Unga',pos: 'RB')
                    .addToPlayers(name:'Brandon Venson',pos: 'TE')
                    .addToPlayers(name:'Eric Weems',pos: 'WR')
                    .save(failOnError: true)

            new Team(name: "Minnesota Vikings")
                    .addToPlayers(name:'Emmanuel Arceneaux',pos: 'WR')
                    .addToPlayers(name:'Devin Aromashodu',pos: 'WR')
                    .addToPlayers(name:'Matt Asiata',pos: 'RB')
                    .addToPlayers(name:'McLeod Bethel-Thompson',pos: 'QB')
                    .addToPlayers(name:'Stephen Burton',pos: 'WR')
                    .addToPlayers(name:'John Carlson',pos: 'TE')
                    .addToPlayers(name:'Greg Childs',pos: 'WR')
                    .addToPlayers(name:'Derrick Coleman',pos: 'RB')
                    .addToPlayers(name:'Ryan DImperio',pos: 'RB')
                    .addToPlayers(name:'Rhett Ellison',pos: 'TE')
                    .addToPlayers(name:'Jerome Felton',pos: 'RB')
                    .addToPlayers(name:'Toby Gerhart',pos: 'RB')
                    .addToPlayers(name:'Percy Harvin',pos: 'WR')
                    .addToPlayers(name:'Lex Hilliard',pos: 'RB')
                    .addToPlayers(name:'Michael Jenkins',pos: 'WR')
                    .addToPlayers(name:'Kamar Jorden',pos: 'WR')
                    .addToPlayers(name:'Adrian Peterson',pos: 'RB')
                    .addToPlayers(name:'Christian Ponder',pos: 'QB')
                    .addToPlayers(name:'Allen Reisner',pos: 'TE')
                    .addToPlayers(name:'Sage Rosenfels',pos: 'QB')
                    .addToPlayers(name:'Kyle Rudolph',pos: 'TE')
                    .addToPlayers(name:'Mickey Shuler',pos: 'TE')
                    .addToPlayers(name:'Jerome Simpson',pos: 'WR')
                    .addToPlayers(name:'Kerry Taylor',pos: 'WR')
                    .addToPlayers(name:'Jordan Todman',pos: 'RB')
                    .addToPlayers(name:'Bryan Walters',pos: 'WR')
                    .addToPlayers(name:'Joe Webb',pos: 'QB')
                    .addToPlayers(name:'Jarius Wright',pos: 'WR')
                    .save(failOnError: true)

            // NFC South
            new Team(name: "New Orleans Saints")
                    .addToPlayers(name:'Adrian Arrington',pos: 'WR')
                    .addToPlayers(name:'Malcolm Beyah',pos: 'WR')
                    .addToPlayers(name:'Drew Brees',pos: 'QB')
                    .addToPlayers(name:'Jake Byrne',pos: 'TE')
                    .addToPlayers(name:'Travaris Cadet',pos: 'RB')
                    .addToPlayers(name:'Sean Canfield',pos: 'QB')
                    .addToPlayers(name:'Jed Collins',pos: 'RB')
                    .addToPlayers(name:'Marques Colston',pos: 'WR')
                    .addToPlayers(name:'Chase Daniel',pos: 'QB')
                    .addToPlayers(name:'Chris Givens',pos: 'WR')
                    .addToPlayers(name:'Jimmy Graham',pos: 'TE')
                    .addToPlayers(name:'Korey Hall',pos: 'RB')
                    .addToPlayers(name:'Kevin Hardy',pos: 'WR')
                    .addToPlayers(name:'Devery Henderson',pos: 'WR')
                    .addToPlayers(name:'Michael Higgins',pos: 'TE')
                    .addToPlayers(name:'Mark Ingram',pos: 'RB')
                    .addToPlayers(name:'Christopher Ivory',pos: 'RB')
                    .addToPlayers(name:'Lance Moore',pos: 'WR')
                    .addToPlayers(name:'Joseph Morgan',pos: 'WR')
                    .addToPlayers(name:'Courtney Roby',pos: 'WR')
                    .addToPlayers(name:'Darren Sproles',pos: 'RB')
                    .addToPlayers(name:'Andy Tanner',pos: 'WR')
                    .addToPlayers(name:'Chris Taylor',pos: 'RB')
                    .addToPlayers(name:'David Thomas',pos: 'TE')
                    .addToPlayers(name:'Pierre Thomas',pos: 'RB')
                    .addToPlayers(name:'Nick Toon',pos: 'WR')
                    .save(failOnError: true)

            new Team(name: "Atlanta Falcons")
                    .addToPlayers(name:'Lamark Brown',pos: 'TE')
                    .addToPlayers(name:'Michael Calvin',pos: 'WR')
                    .addToPlayers(name:'Kevin Cone',pos: 'WR')
                    .addToPlayers(name:'Mike Cox',pos: 'RB')
                    .addToPlayers(name:'Dominique Davis',pos: 'QB')
                    .addToPlayers(name:'Drew Davis',pos: 'WR')
                    .addToPlayers(name:'Harry Douglas',pos: 'WR')
                    .addToPlayers(name:'Bradie Ewing',pos: 'RB')
                    .addToPlayers(name:'Robbie Frey',pos: 'RB')
                    .addToPlayers(name:'Tommy Gallarda',pos: 'TE')
                    .addToPlayers(name:'Tony Gonzalez',pos: 'TE')
                    .addToPlayers(name:'Marcus Jackson',pos: 'WR')
                    .addToPlayers(name:'Julio Jones',pos: 'WR')
                    .addToPlayers(name:'Kerry Meier',pos: 'WR')
                    .addToPlayers(name:'Lee Meisner',pos: 'RB')
                    .addToPlayers(name:'Dimitri Nance',pos: 'RB')
                    .addToPlayers(name:'Adam Nissley',pos: 'TE')
                    .addToPlayers(name:'Michael Palmer',pos: 'TE')
                    .addToPlayers(name:'Cody Pearcy',pos: 'WR')
                    .addToPlayers(name:'Chris Redman',pos: 'QB')
                    .addToPlayers(name:'Jacquizz Rodgers',pos: 'RB')
                    .addToPlayers(name:'James Rodgers',pos: 'WR')
                    .addToPlayers(name:'Matt Ryan',pos: 'QB')
                    .addToPlayers(name:'Antone Smith',pos: 'RB')
                    .addToPlayers(name:'Jason Snelling',pos: 'RB')
                    .addToPlayers(name:'Kenny Stafford',pos: 'WR')
                    .addToPlayers(name:'Michael Turner',pos: 'RB')
                    .addToPlayers(name:'Aron White',pos: 'TE')
                    .addToPlayers(name:'Roddy White',pos: 'WR')
                    .addToPlayers(name:'John Parker Wilson',pos: 'QB')
                    .addToPlayers(name:'Joe Zelenka',pos: 'TE')
                    .save(failOnError: true)

            new Team(name: "Carolina Panthers")
                    .addToPlayers(name:'Darvin Adams',pos: 'WR')
                    .addToPlayers(name:'Joe Adams',pos: 'WR')
                    .addToPlayers(name:'Seyi Ajirotutu',pos: 'WR')
                    .addToPlayers(name:'Derek Anderson',pos: 'QB')
                    .addToPlayers(name:'Gary Barnidge',pos: 'TE')
                    .addToPlayers(name:'Brenton Bersin',pos: 'WR')
                    .addToPlayers(name:'Richie Brockel',pos: 'TE')
                    .addToPlayers(name:'Jimmy Clausen',pos: 'QB')
                    .addToPlayers(name:'Armanti Edwards',pos: 'WR')
                    .addToPlayers(name:'David Gettis',pos: 'WR')
                    .addToPlayers(name:'Jared Green',pos: 'WR')
                    .addToPlayers(name:'Ben Hartsock',pos: 'TE')
                    .addToPlayers(name:'Dwayne Jarrett',pos: 'WR')
                    .addToPlayers(name:'Wes Kemp',pos: 'WR')
                    .addToPlayers(name:'Brandon LaFell',pos: 'WR')
                    .addToPlayers(name:'Tarren Lloyd',pos: 'TE')
                    .addToPlayers(name:'Chris Manno',pos: 'WR')
                    .addToPlayers(name:'Princeton McCarty',pos: 'RB')
                    .addToPlayers(name:'Cam Newton',pos: 'QB')
                    .addToPlayers(name:'Greg Olsen',pos: 'TE')
                    .addToPlayers(name:'Kealoha Pilares',pos: 'WR')
                    .addToPlayers(name:'Tauren Poole',pos: 'RB')
                    .addToPlayers(name:'Lyndon Rowells',pos: 'RB')
                    .addToPlayers(name:'Armond Smith',pos: 'RB')
                    .addToPlayers(name:'Greg Smith',pos: 'TE')
                    .addToPlayers(name:'Steve Smith',pos: 'WR')
                    .addToPlayers(name:'Jonathan Stewart',pos: 'RB')
                    .addToPlayers(name:'Mike Tolbert',pos: 'RB')
                    .addToPlayers(name:'Josh Vaughan',pos: 'RB')
                    .addToPlayers(name:'Rico Wallace',pos: 'WR')
                    .addToPlayers(name:'DeAngelo Williams',pos: 'RB')
                    .save(failOnError: true)

            new Team(name: "Tampa Bay Buccaneers")
                    .addToPlayers(name:'Arrelious Benn',pos: 'WR')
                    .addToPlayers(name:'LeGarrette Blount',pos: 'RB')
                    .addToPlayers(name:'Dezmon Briscoe',pos: 'WR')
                    .addToPlayers(name:'Chase Coffman',pos: 'TE')
                    .addToPlayers(name:'DeAnthony Curtis',pos: 'RB')
                    .addToPlayers(name:'Drake Dunsmore',pos: 'TE')
                    .addToPlayers(name:'Collin Franklin',pos: 'TE')
                    .addToPlayers(name:'Josh Freeman',pos: 'QB')
                    .addToPlayers(name:'Ed Gant',pos: 'WR')
                    .addToPlayers(name:'Robert Hughes',pos: 'RB')
                    .addToPlayers(name:'Vincent Jackson',pos: 'WR')
                    .addToPlayers(name:'Cody Johnson',pos: 'RB')
                    .addToPlayers(name:'Antonio Leak',pos: 'RB')
                    .addToPlayers(name:'Armahd Lewis',pos: 'WR')
                    .addToPlayers(name:'Erik Lorig',pos: 'RB')
                    .addToPlayers(name:'Mossis Madu',pos: 'RB')
                    .addToPlayers(name:'Doug Martin',pos: 'RB')
                    .addToPlayers(name:'Danny Noble',pos: 'TE')
                    .addToPlayers(name:'Dan Orlovsky',pos: 'QB')
                    .addToPlayers(name:'Preston Parker',pos: 'WR')
                    .addToPlayers(name:'Zack Pianalto',pos: 'TE')
                    .addToPlayers(name:'Brett Ratliff',pos: 'QB')
                    .addToPlayers(name:'Tyler Shoemaker',pos: 'WR')
                    .addToPlayers(name:'Michael Smith',pos: 'RB')
                    .addToPlayers(name:'Luke Stocker',pos: 'TE')
                    .addToPlayers(name:'Sammie Stroughter',pos: 'WR')
                    .addToPlayers(name:'Tiquan Underwood',pos: 'WR')
                    .addToPlayers(name:'Mike Williams',pos: 'WR')
                    .addToPlayers(name:'Kellen Winslow',pos: 'TE')
                    .addToPlayers(name:'Wallace Wright',pos: 'WR')
                    .save(failOnError: true)

            // NFC West
            new Team(name: "San Francisco 49ers")
                    .addToPlayers(name:'Cameron Bell',pos: 'RB')
                    .addToPlayers(name:'Nate Byham',pos: 'TE')
                    .addToPlayers(name:'Rock Cartwright',pos: 'RB')
                    .addToPlayers(name:'Garrett Celek',pos: 'TE')
                    .addToPlayers(name:'Michael Crabtree',pos: 'WR')
                    .addToPlayers(name:'Vernon Davis',pos: 'TE')
                    .addToPlayers(name:'Anthony Dixon',pos: 'RB')
                    .addToPlayers(name:'Ted Ginn Jr.',pos: 'WR')
                    .addToPlayers(name:'Frank Gore',pos: 'RB')
                    .addToPlayers(name:'Jewel Hampton',pos: 'RB')
                    .addToPlayers(name:'Joe Hastings',pos: 'WR')
                    .addToPlayers(name:'Kendall Hunter',pos: 'RB')
                    .addToPlayers(name:'Brandon Jacobs',pos: 'RB')
                    .addToPlayers(name:'LaMichael James',pos: 'RB')
                    .addToPlayers(name:'A.J. Jenkins',pos: 'WR')
                    .addToPlayers(name:'Brian Jennings',pos: 'TE')
                    .addToPlayers(name:'Josh Johnson',pos: 'QB')
                    .addToPlayers(name:'Colin Kaepernick',pos: 'QB')
                    .addToPlayers(name:'Mario Manningham',pos: 'WR')
                    .addToPlayers(name:'Bruce Miller',pos: 'RB')
                    .addToPlayers(name:'Randy Moss',pos: 'WR')
                    .addToPlayers(name:'Kyle Nelson',pos: 'TE')
                    .addToPlayers(name:'Chris Owusu',pos: 'WR')
                    .addToPlayers(name:'Nathan Palmer',pos: 'WR')
                    .addToPlayers(name:'Konrad Reuland',pos: 'TE')
                    .addToPlayers(name:'Alex Smith',pos: 'QB')
                    .addToPlayers(name:'Brett Swain',pos: 'WR')
                    .addToPlayers(name:'Scott Tolzien',pos: 'QB')
                    .addToPlayers(name:'Brian Tyms',pos: 'WR')
                    .addToPlayers(name:'Delanie Walker',pos: 'TE')
                    .addToPlayers(name:'Kyle Williams',pos: 'WR')
                    .save(failOnError: true)

            new Team(name: "Arizona Cardinals")
                    .addToPlayers(name:'Stanley Arukwe',pos: 'WR')
                    .addToPlayers(name:'Richard Bartel',pos: 'QB')
                    .addToPlayers(name:'LaRon Byrd',pos: 'WR')
                    .addToPlayers(name:'Jared Crank',pos: 'RB')
                    .addToPlayers(name:'Early Doucet',pos: 'WR')
                    .addToPlayers(name:'Jim Dray',pos: 'TE')
                    .addToPlayers(name:'Larry Fitzgerald',pos: 'WR')
                    .addToPlayers(name:'Michael Floyd',pos: 'WR')
                    .addToPlayers(name:'Tre Gray',pos: 'WR')
                    .addToPlayers(name:'Todd Heap',pos: 'TE')
                    .addToPlayers(name:'Rob Housler',pos: 'TE')
                    .addToPlayers(name:'Javarris James',pos: 'RB')
                    .addToPlayers(name:'Jaymar Johnson',pos: 'WR')
                    .addToPlayers(name:'Jeff King',pos: 'TE')
                    .addToPlayers(name:'Kevin Kolb',pos: 'QB')
                    .addToPlayers(name:'Mike Leach',pos: 'TE')
                    .addToPlayers(name:'Ryan Lindley',pos: 'QB')
                    .addToPlayers(name:'William Powell',pos: 'RB')
                    .addToPlayers(name:'Andre Roberts',pos: 'WR')
                    .addToPlayers(name:'DeMarco Sampson',pos: 'WR')
                    .addToPlayers(name:'Anthony Sherman',pos: 'RB')
                    .addToPlayers(name:'John Skelton',pos: 'QB')
                    .addToPlayers(name:'Steve Skelton',pos: 'TE')
                    .addToPlayers(name:'Alfonso Smith',pos: 'RB')
                    .addToPlayers(name:'LaRod Stephens-Howling',pos: 'RB')
                    .addToPlayers(name:'Martell Webb',pos: 'TE')
                    .addToPlayers(name:'Beanie Wells',pos: 'RB')
                    .addToPlayers(name:'Isaiah Williams',pos: 'WR')
                    .addToPlayers(name:'Ryan Williams',pos: 'RB')
                    .addToPlayers(name:'Stephen Williams',pos: 'WR')
                    .addToPlayers(name:'Marc Wilson',pos: 'WR')
                    .save(failOnError: true)

            new Team(name: "Seattle Seahawks")
                    .addToPlayers(name:'Doug Baldwin',pos: 'WR')
                    .addToPlayers(name:'Phil Bates',pos: 'WR')
                    .addToPlayers(name:'Deon Butler',pos: 'WR')
                    .addToPlayers(name:'Kris Durham',pos: 'WR')
                    .addToPlayers(name:'Matt Flynn',pos: 'QB')
                    .addToPlayers(name:'Cooper Helfet',pos: 'TE')
                    .addToPlayers(name:'Tarvaris Jackson',pos: 'QB')
                    .addToPlayers(name:'Jermaine Kearse',pos: 'WR')
                    .addToPlayers(name:'Ricardo Lockette',pos: 'WR')
                    .addToPlayers(name:'Kregg Lumpkin',pos: 'RB')
                    .addToPlayers(name:'Marshawn Lynch',pos: 'RB')
                    .addToPlayers(name:'Charly Martin',pos: 'WR')
                    .addToPlayers(name:'Anthony McCoy',pos: 'TE')
                    .addToPlayers(name:'Sean McGrath',pos: 'TE')
                    .addToPlayers(name:'Zach Miller',pos: 'TE')
                    .addToPlayers(name:'Cameron Morrah',pos: 'TE')
                    .addToPlayers(name:'John Nalbone',pos: 'TE')
                    .addToPlayers(name:'Ben Obomanu',pos: 'WR')
                    .addToPlayers(name:'Josh Portis',pos: 'QB')
                    .addToPlayers(name:'Sidney Rice',pos: 'WR')
                    .addToPlayers(name:'Michael Robinson',pos: 'RB')
                    .addToPlayers(name:'Tyrell Sutton',pos: 'RB')
                    .addToPlayers(name:'Golden Tate',pos: 'WR')
                    .addToPlayers(name:'Vai Taua',pos: 'RB')
                    .addToPlayers(name:'Lavasier Tuinei',pos: 'WR')
                    .addToPlayers(name:'Robert Turbin',pos: 'RB')
                    .addToPlayers(name:'Leon Washington',pos: 'RB')
                    .addToPlayers(name:'Mike Williams',pos: 'WR')
                    .addToPlayers(name:'Russell Wilson',pos: 'QB')
                    .save(failOnError: true)

            new Team(name: "St. Louis Rams")
                    .addToPlayers(name:'Danario Alexander',pos: 'WR')
                    .addToPlayers(name:'Danny Amendola',pos: 'WR')
                    .addToPlayers(name:'Todd Anderson',pos: 'RB')
                    .addToPlayers(name:'Sam Bradford',pos: 'QB')
                    .addToPlayers(name:'Tom Brandstater',pos: 'QB')
                    .addToPlayers(name:'Kellen Clemens',pos: 'QB')
                    .addToPlayers(name:'Austin Davis',pos: 'QB')
                    .addToPlayers(name:'Brandon Gibson',pos: 'WR')
                    .addToPlayers(name:'Chris Givens',pos: 'WR')
                    .addToPlayers(name:'Ben Guidugli',pos: 'TE')
                    .addToPlayers(name:'Cory Harkey',pos: 'TE')
                    .addToPlayers(name:'Michael Hoomanawanui',pos: 'TE')
                    .addToPlayers(name:'Steven Jackson',pos: 'RB')
                    .addToPlayers(name:'Nicholas Johnson',pos: 'WR')
                    .addToPlayers(name:'Lance Kendricks',pos: 'TE')
                    .addToPlayers(name:'Mike McNeill',pos: 'TE')
                    .addToPlayers(name:'Calvin Middleton',pos: 'RB')
                    .addToPlayers(name:'Brit Miller',pos: 'RB')
                    .addToPlayers(name:'Nick Miller',pos: 'WR')
                    .addToPlayers(name:'Matthew Mulligan',pos: 'TE')
                    .addToPlayers(name:'Isaiah Pead',pos: 'RB')
                    .addToPlayers(name:'Deangelo Peterson',pos: 'TE')
                    .addToPlayers(name:'Austin Pettis',pos: 'WR')
                    .addToPlayers(name:'Brian Quick',pos: 'WR')
                    .addToPlayers(name:'Chase Reynolds',pos: 'RB')
                    .addToPlayers(name:'Daryl Richardson',pos: 'RB')
                    .addToPlayers(name:'Greg Salas',pos: 'WR')
                    .addToPlayers(name:'Nick Schwieger',pos: 'RB')
                    .addToPlayers(name:'Steve Smith',pos: 'WR')
                    .save(failOnError: true)

            println "***" + Team.count() + " total teams***"

        } // End Add Teams

    }
    def destroy = {
    }
}
